### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by ttodua** [michaeldrennen/td-ameritrade-api#1]
Hi. Aren't there any examples of usage?

**Comment by michaeldrennen** [comment]
Sorry for the delay. I wrote this for a project I'm actively working on, so I haven't made the time to document this at all.

I will definitely get to the documentation, but I can say that the API works great. 

I have been trading with it since December.

**Comment by ttodua** [comment]
thanks for response.

Just few examples even, how to use/trigger this or that commands might have been any help.
I dont say the full documentation that is done for official programs... even a voluntary examples might have been useful.

**Comment by michaeldrennen** [comment]
Added a tiny bit of documentation to the README.
